### ISSUE TITLE
FormGetFocusedText

### ISSUE THREAD

**Issue by kjteng** [ahausladen/PdfiumLib#25]
Hi, I keep geting blank string from FormGetFocusedText (and other methods relating to fillable form in pdf) even when I call the dll function directrly. Do I need to perform some other procedures before I can call FormGetFocusedText?  or is this due to issue in the dll functions (as you have marked them as 'Experimental API')? 
Thank you.

**Comment by ahausladen** [comment]
FORM_GetFocusedText only returns something if the PDF form field is currently selected. If you put the function behind a button and you press that button, the focus is switched to the button and when you then call the FORM_GetFocusedText function it returns an empty string.

In a simple test app, I put the function in a timer event and the moment I typed in the PDF form field, the function returned the text of the form field.
The same happens with FORM_GetSelectedText. Only if the PDF form field has the focus, it returns the value.

**Comment by kjteng** [comment]
Thank you for the pointer. It means that we should use speedbutton (or other component which would not get focus) to trigger these methods.  Tqtq.
