### ISSUE TITLE
How to write to form field?

### ISSUE THREAD

**Issue by LuWey** [ahausladen/PdfiumLib#26]
I understand form fields are actually annotations and I managed to read them using the FPDFAnnot_GetFormXXX functions. What I am missing is some kind of FPDFAnnot_SetFormValue function. I already played with FPDFAnnot_SetAP and FPDFAnnot_SetStringValue but this didn't work, 

Question: 

Is there some kind of "FPDFAnnot_SetFormValue" function hidden somewhere? If not, are FPDFAnnot_SetAP and FPDFAnnot_SetStringValue the way to go and if so, how to correctly use them?

Thank you for your help!

**Comment by ahausladen** [comment]
dfda36edefe0415d8ab358a74cbd4ad1f6479331 adds FormFields property to the TPdfPage class that allows changing the text value, the checkbox/radiobutton checked state and the selected combobox/listbox items.

**Comment by LuWey** [comment]
Wow, that was fast! Thank you so much!
