### ISSUE TITLE
Create Annotations

### ISSUE THREAD

**Issue by xelnaga64** [ahausladen/PdfiumLib#29]
Hello,

Is it possible to create new annotations programmatically?
And of course, they must be included when saving as PDF (Document.SaveToFile), just like form fields.

Thank you for your great work!

**Comment by ahausladen** [comment]
You can use FPDFPage_CreateAnnot and then the FPDFAnnot_Xxxx function in PdfiumLib to add annotations by code.

**Comment by xelnaga64** [comment]
Something like `FCtrl.CurrentPage.Annotations.Add('Hello',100,100,200,200)` would be great!
