### ISSUE TITLE
System Error. Code: 126.

### ISSUE THREAD

**Issue by engerex** [ahausladen/PdfiumLib#31]
System Error. Code: 126.
Delphi 11 Community Edition
Windows 11 pro x64
I tested : pdfium.dll 5744:
x64 EXE : pdfium-win-x64.tgz, pdfium-v8-win-x64.tgz
x86 EXE : pdfium-win-x86.tgz
![image](https://github.com/ahausladen/PdfiumLib/assets/5686053/8f87f0a4-3bea-44b6-bd3d-73019048b069)

**Comment by Dingo64** [comment]
You need to put your pdfium.dll here:
C:\Works\Uygulama\Samples\PDF\ahausladen - PdfiumLib-master\Example\Win64\Debug\
