### ISSUE TITLE
Access violation in 32 bit

### ISSUE THREAD

**Issue by Dingo64** [ahausladen/PdfiumLib#32]
Not exactly the right place but maybe someone can help.
I got a Lazarus port (https://github.com/kjteng/PdfiumLib/) and works great in 64 bit. But in 32 bit I get access violation when trying to highlight:
```
function TPdfPage.GetTextRect(RectIndex: Integer): TPdfRect;
begin
  if BeginText then
    FPDFText_GetRect(FTextHandle, RectIndex, Result.Left, Result.Top, Result.Right, Result.Bottom); //this crashes
  end
  else
    Result := TPdfRect.Empty;
end; 
```
I don't know what could be wrong. I tried different versions of DLL but no change.
I made a simple demo which shows the problem:
http://mazurlazur.pl/simplest.zip

**Comment by ahausladen** [comment]
Shouldn't you report this to the FPC fork where it happens? I can't reproduce this bug with a Delphi compiled 32 bit application.
