### ISSUE TITLE
Some PDF files are shown with a black background

### ISSUE THREAD

**Issue by xelnaga64** [ahausladen/PdfiumLib#35]
Some PDF files are shown with a black background, text is unreadable. When I open the same PDF file using Adobe Reader or Edge, the background is white. Any idea or suggestion?

**Comment by ahausladen** [comment]
Do you have an example PDF. None of the PDFs I have show "black background".

**Comment by xelnaga64** [comment]
https://www.dropbox.com/scl/fi/jqs0e35h670we90rleu7u/problem.pdf?rlkey=s5czl9owpvl0lmw23uthynzs9&dl=0
