### ISSUE TITLE
Incompatible types: 'TPdfAnnotation' and 'FPDF_ANNOTATION'

### ISSUE THREAD

**Issue by xelnaga64** [ahausladen/PdfiumLib#38]
I get this compile error after the latest update: Incompatible types: 'TPdfAnnotation' and 'FPDF_ANNOTATION'

In this file: PdfiumCore.pas
In line 3732: FFormField := TPdfFormField.Create(FHandle);

Using Delphi 10.3.3

**Comment by ahausladen** [comment]
Some Delphi compilers (especially the one that I use to develop PdfiumLib) accept that broken code. With an older Delphi version, the compiler wasn't happy about that code line.

**Comment by xelnaga64** [comment]
Thank you very much for your splendid work ❤️
