### ISSUE TITLE
PDF-A Flag

### ISSUE THREAD

**Issue by RalfPM** [ahausladen/PdfiumLib#41]
Hello,
is it possible to get Information if an loaded PDF has the PDF-A Flag?

Or if not is it possible to read or get the xmpmeta to look inside to get the PDF-A Information on my own.

Thanks a lot and best regards
Ralf

**Comment by ahausladen** [comment]
You could try with FPDF_GetMetaText()
But as far as I can see, PDFium doesn't supports reading the xmpmeta Tag.

**Comment by RalfPM** [comment]
That is the same that i found. There are two thinks i fink would be not bad
1. Have a PDF-A flag
2. A Way to get the hole MetaData

**Comment by ahausladen** [comment]
For this you have to create a bug report for the PDFium project.
https://bugs.chromium.org/p/pdfium/issues/list
