### ISSUE TITLE
Annotation still experimental?

### ISSUE THREAD

**Issue by RalfPM** [ahausladen/PdfiumLib#42]
Hello,
I want to give my customer a chance to use Annotations. Are they still experimental? Or is it plant that they be really can be used.

What i want is to add Highlight and something like a memo. Is that possible and have you an example how to work with them?

Thanks a lot and best regards
Ralf

**Comment by ahausladen** [comment]
The whole Annotations API is marked as "Experimental API" in PDFium. So it is also experimental in PDFiumLib.

The example project shows how to add a text annotation (TfrmMain.btnAddAnnotationClick). But there is no user interaction with that annotation implemented (move, delete, edit). It is just an example project, not a full featured PDF viewer.

**Comment by RalfPM** [comment]
Hello Herr Hausladen,

thanks for your feedback. At the moment then i will not start to try to use the annotations.

Best regards
Ralf
