### ISSUE TITLE
Rename FPDFFont_GetFontName() to FPDFFont_GetFamilyName()

### ISSUE THREAD

**Issue by mirkasp** [ahausladen/PdfiumLib#44]
DLL function "FPDFFont_GetFontName" was renamed to "FPDFFont_GetFamilyName"
https://pdfium.googlesource.com/pdfium/+/2f4d4841a15e9ca16ad9c66d4f97bda1535ab255

btw: PdfiumLib is super!

**Comment by ahausladen** [comment]
Fixed with b9487a55bdc0076767bd0802821cc108b118bb6a (Updated to chromium/6611)
