### ISSUE TITLE
X86 OK, X64 Error

### ISSUE THREAD

**Issue by dbyoung720** [ahausladen/PdfiumLib#6]
X86 OK, X64 Error

**Comment by magnolima** [comment]
Can't load DLL.
 Exception class Exception with message 'Symbol "_FPDF_InitLibrary@0" was not found in pdfium.dll'. 

None x86 or x64 can be loaded. Any clue?

**Comment by danieleteti** [comment]
Any news on this?

**Comment by ahausladen** [comment]
The Pdfium 3751 DLL works, but the newer DLLs switch from stdcall to cdecl. I doubt that was indented. I don't know if I should just do a string replace for "stdcall" to "cdecl" and remove the "@paramcount" from the symbol names, or if I should just wait for them to fix it.

**Comment by magnolima** [comment]
> The Pdfium 3751 DLL works, but the newer DLLs switch from stdcall to cdecl. I doubt that was indented. I don't know if I should just do a string replace for "stdcall" to "cdecl" and remove the "@paramcount" from the symbol names, or if I should just wait for them to fix it.

Thank you!! Can I use an older DLL? If yes, where could I take and what version do you recommend?

**Comment by ahausladen** [comment]
> where could I take and what version do you recommend?

https://github.com/bblanchon/pdfium-binaries/releases

Release 3751

**Comment by magnolima** [comment]
> > where could I take and what version do you recommend?
> 
> https://github.com/bblanchon/pdfium-binaries/releases
> 
> Release 3751

Yeah, I read just after sent the message! Thank you! It works perfectly!! 👍

**Comment by dbyoung720** [comment]
3751 x64 problem remains.

**Comment by magnolima** [comment]
> 3751 x64 problem remains.

The 32bit version is working fine here, give a try.

**Comment by percy-schott** [comment]
Hi 
ich habe Probleme die 64-Bit variante zum laufen zu bringen.
Ich bekomme immer den Fehler FLOAT_INVALID_OPERATION sobald ich FPDFText_LoadPage aufrufe. Hat jemand eine Lösung? Ich habe die Versionen 3751 und 3866 (mit Konvertierung nach CDECL) von  https://github.com/bblanchon/pdfium-binaries ausprobiert aber bisher keinen Erfolg gehabt.

Hi
I have problems running the 64-bit variant.
I always get the error FLOAT_INVALID_OPERATION as soon as I call FPDFText_LoadPage. Does anyone have a solution? I've tried versions 3751 and 3866 (with conversion to CDECL) from https://github.com/bblanchon/pdfium-binaries but have not had success so far.


procedure TForm7.btnAllClick(Sender: TObject);
var
  oConfig: TFPdfLibraryConfig;
  oTextPage: FPDF_TEXTPAGE;
  sFileName: AnsiString;
  iChars: Integer;
  sHelp: string;
begin
  foDocument := nil;
  foPage := nil;
  oConfig.version := 2;
  oConfig.m_pUserFontPaths := nil;
  oConfig.m_pIsolate := nil;
  oConfig.m_v8EmbedderSlot := 0;
  FPDF_InitLibraryWithConfig(@oConfig);
  if OpenDialog1.Execute(Handle) then
  begin
    sFileName := OpenDialog1.FileName;
    foDocument := FPDF_LoadDocument(PAnsiChar(sFileName), '');
    SpinEdit1.Value := 0;
  end;
  Memo1.Clear;
  if Assigned(foDocument) then
  begin
    Memo1.Lines.Add(FPDF_GetPageCount(foDocument).ToString);
    SpinEdit1.MaxValue := FPDF_GetPageCount(foDocument) - 1;
  end;
  if Assigned(foPage) then
  begin
    FPDF_ClosePage(foPage);
    foPage := nil;
  end;
  foPage := FPDF_LoadPage(foDocument, SpinEdit1.Value);
  Memo1.Clear;
  if Assigned(foPage) then
  begin
    oTextPage := FPDFText_LoadPage(foPage);
    if Assigned(oTextPage) then
    begin
      iChars := FPDFText_CountChars(oTextPage);
      Memo1.Lines.Add(iChars.ToString);
      if iChars > 0 then
      begin
        SetLength(sHelp, iChars + 2);
        iChars := FPDFText_GetText(oTextPage, 0, iChars, PChar(sHelp));
        SetLength(sHelp, iChars);
        Memo1.Lines.Add(sHelp);
      end;
      FPDFText_ClosePage(oTextPage);
      oTextPage := nil;
    end;
  end;
  if Assigned(foPage) then
  begin
    FPDF_ClosePage(foPage);
    foPage := nil;
  end;
  if Assigned(foDocument) then
  begin
    FPDF_CloseDocument(foDocument);
    foDocument := nil;
    SpinEdit1.Value := -1;
  end;
  FPDF_DestroyLibrary;
  foDocument := nil;
  foPage := nil;

end;

**Comment by percy-schott** [comment]
Wenn ich die Debug Version von https://github.com/bblanchon/pdfium-binaries in 64-Bit verwende funktioniert es.

When I use the debug version of https://github.com/bblanchon/pdfium-binaries in 64-bit it works

**Comment by percy-schott** [comment]
Okay the solution is SetExceptionMask(exAllArithmeticExceptions);
