### ISSUE TITLE
Issue when more than 20.000 pages (scanning pages) - my file 201.000 pages

### ISSUE THREAD

**Issue by seandollard-evercalc** [ahausladen/PdfiumLib#9]
Thank You for a great product.

I tried again and again with program failure (scanning all pages of PDF file, failed after 20.000+, 30.000+, 40.000+ pages) - the program just shut down - until I discovered the following modification solved all my issues:

procedure TPdfControl.SetPageIndex(Value: Integer);
begin
  // 2019.12.07
  if (Value >= 0) and (Value < PageCount) and (Value <> FPageIndex) and (FPageIndex <> FRenderedPageIndex) then
    if Assigned(FDocument.Pages[FPageIndex]) then
      FDocument.Pages[FPageIndex].Close;

  InternSetPageIndex(Value, False, False);
end;

Please consider for future version maybe as an option.

PS. I rewrote the units for Delphi 6 (believe it or not) on request. Works fine.

Sean Dollard, Denmark

**Comment by ahausladen** [comment]
This is now fixed. FRenderedPageIndex wasn't the best way to detect if a page was loaded or not.
